### ISSUE TITLE
완성도 있는 코드 작성하기

### ISSUE THREAD

**Issue by parkjisu6239** [parkjisu6239/Dicoco#10]
### Todo
- [ ] [HTML 요소](https://developer.mozilla.org/ko/docs/Web/HTML/Element), Semantic Tag 를 적절히 사용하여 명시적으로 코딩하기
- [ ] [키보드 접근성](https://webaim.org/techniques/keyboard/)
- [ ] [코드 분할](https://ko.reactjs.org/docs/code-splitting.html)
- [ ] 모듈화하기

### More
- [ ] TypeScripts 적용하기
- [ ] Redux 적용하기(필요하다면 사용, 아니라면 굳이 사용할 이유 없음)
- [ ] Next.js 적용하기(랜더링 차이 및 성능 차이 확인해보기)
