### ISSUE TITLE
Chat Todo

### ISSUE THREAD

**Issue by parkjisu6239** [parkjisu6239/Dicoco#3]
### Todo

- [x] #5
- [x] Session 이름은 영문만 지원한다고 써주기
- [x] Name, Session 길이 제한
- [x] enter/exit 공지 bold
- [x] chat 내용에서 사람 이름 bold
- [x] Easter Egg
